### PR TITLE
Added RandomWOW support

### PR DESCRIPTION
**Pull request by SChernykh**

### CODE REVIEW

**Comment by Spudz76** [comment]
How does this work, tried with the same randomx lib as the cpu miner uses and it seems to fail spectacularly.

**Comment by SChernykh** [comment]
It's better to wait until I integrate RandomX this week. If you want to try now, you need a lib compiled from https://github.com/wownero/RandomWOW

**Comment by Spudz76** [comment]
Yeah, I tried using your RandomX_CUDA repo also, built the lib ok (with same gcc-7 as used throughout xmrig-nvidia compile), but get the same sort of results:
```
[2019-07-02 19:30:47] new job from 127.0.0.1:3334 diff -1 algo rx/wow
[CUDA] Error gpu 0: <randomx_prepare>:60 "out of memory"
```
gcc-7 cuda9.1 arch30 driver390.116

Are there minimal requirements for this?  I did not try (yet) to make the benchmark/test portion and validate the lib is working, on same GPU.

**Comment by SChernykh** [comment]
Ah, this is auto-config not working correctly. You need to reduce threads/blocks.

**Comment by Spudz76** [comment]
So this is why 1x1 crashes, it doesn't pass the mod32 and ends up as 0
```
[2019-07-03 11:49:27] new job from 127.0.0.1:3334 diff -1 algo rx/wow
[2019-07-03 11:49:27] batch_size 1
[2019-07-03 11:49:27] batch_size 1
[2019-07-03 11:49:27] RX prepare with batch_size 0
[CUDA] Error gpu 0: <randomx_prepare>:60 "out of memory"
```

However 8x4 comes up with the smallest mod32 valid size (and tiny) but it still fails
```
[2019-07-03 11:54:30] new job from 127.0.0.1:3334 diff -1 algo rx/wow
[2019-07-03 11:54:30] batch_size 32
[2019-07-03 11:54:30] batch_size 32
[2019-07-03 11:54:30] RX prepare with batch_size 32
[CUDA] Error gpu 0: <randomx_prepare>:60 "out of memory"
```

CN-Lite runs just fine (at 128x8) and is the same scratchpad size, what gives.

I have 16GB swap (up from 2GB originally) and 16GB ram, hugepages enabled, etc.
` * GPU #0       PCI:0000:01:00 Quadro K1100M @ 705/1733 MHz 8x4 8x100 arch:30 SMX:2 MEM:1459/1999 MiB`

Does this algo require 2080MB available on GPU?  If so then of course it will never work on this (and all my other CN-nvidia rigs... if they have 4+GB they run ethash).

**Comment by SChernykh** [comment]
Yes, it needs 2080 MB + 1 MB for each scratchpad (for Wownero) on GPU.

**Comment by Spudz76** [comment]
eww nasty, it might as well be dagger-hashimoto then

When will you have xmrig-amd support done, I actually do have enough memory on the V64's

**Pull request merged**
